# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 11:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('skills', '0001_initial'),
        ('users', '0002_auto_20170220_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='skills',
            field=models.ManyToManyField(through='users.UserSkills', to='skills.Skills'),
        ),
    ]
