# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 11:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('skills', '0002_auto_20170301_1128'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRequiresSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Missions')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Skills')),
            ],
        ),
        migrations.AddField(
            model_name='missions',
            name='skills',
            field=models.ManyToManyField(through='missions.MissionRequiresSkills', to='skills.Skills'),
        ),
    ]
