# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.AddField(
            model_name='skills',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
